In [18]:
import tensorflow as tf
tf.__version__

'2.3.0'

In [19]:

import numpy as np
import sklearn as sk
import seaborn as sns
import tensorflow.compat.v1 as tf
tf.disable_eager_execution()
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
import os

In [20]:
a = tf.Variable(80, name = 'a')   
b = tf.Variable(6, name = 'b')
c = (a ** 1/b)

with tf.Session() as sess:
  init = tf.global_variables_initializer()
  init.run()
  result = c.eval()
  

In [21]:
result

13.333333333333334

Creating a constant


In [22]:
a = tf.constant(989)
b = a + 8767
c = b - 978

with tf.Session() as sess:
    #init = tf.global_variables_initializer()
    init.run()
    d = c.eval()
d    

8778

Creating a Matrix

In [23]:
a = tf.ones((10,5))
b = tf.zeros((5,10))
c = tf.ones((10,10))

y = tf.matmul(a,b) + c

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    init.run()
    matrix = y.eval()
    
print(matrix)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


Matrix determinant

In [24]:
arr = np.array([[2.0,4.0,6.6],
                [6.6,8.2,1.1],
                [7.4,4.1,2.9]])
det = tf.matrix_determinant(arr)
with tf.Session() as sess:
    out = det.eval()
    print(out)

-227.352


In [25]:
# transpose
trans = tf.matrix_transpose(arr)
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    init.run()
    tran = trans.eval()
    print(tran)

[[2.  6.6 7.4]
 [4.  8.2 4.1]
 [6.6 1.1 2.9]]


In [26]:
# max args
max = tf.argmax([3,4,18,7], name = 'max' )
with tf.Session() as sess:
    print(max.eval())

2


In [27]:
# min args
min = tf.argmin([3,4,18,7], name = 'min')
with tf.Session() as sess:
    print(min.eval())

0


In [29]:
# argmax according to axis

arg = tf.argmax(arr, axis = 1)
with tf.Session() as sess:
    nit = tf.global_variables_initializer()
    init.run()
    print(arg.eval())

[2 1 0]


In [30]:
# Arg sorting
b = tf.argsort(arr,axis=1,direction='ASCENDING',name='b')
c = tf.keras.backend.eval(b)
print(c)

[[0 1 2]
 [2 0 1]
 [2 1 0]]


In [31]:
arr

array([[2. , 4. , 6.6],
       [6.6, 8.2, 1.1],
       [7.4, 4.1, 2.9]])

In [32]:
# confusion matrix
a = tf.random_uniform((90,),minval = 0, maxval = 1)
b = tf.random_uniform((90,), minval = 0, maxval =1)
pred = tf.round(a, 'pred')
y_true = tf.round(b,'y_true')
confusion_mat = tf.confusion_matrix(pred, y_true, name = 'confusion_Matrix')
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    init.run()
    print(confusion_mat.eval())

[[20 20]
 [22 28]]


In [33]:
# cast - casting a tensor to a new type
x = tf.constant([1.8,2.2, 3.5,4.9], dtype = tf.float32)
rea = tf.dtypes.cast(x, tf.int32)
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    init.run()
    print(rea.eval())

[1 2 3 4]


In [34]:
# cummulative sum
cum_sum = tf.cumsum(x, axis = 0, name = 'cum_sum')
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    init.run()
    print(cum_sum.eval())

[ 1.8  4.   7.5 12.4]


Place Holders

In [35]:
A = tf.placeholder(tf.float32, shape = (None,3))
B = A + 5

with tf.Session() as sess:
    b_val = B.eval(feed_dict = {A:[[1,2,3]]})
    b_val_u = B.eval(feed_dict = {A:[[4,5,6],[7,8,9]]})
print(b_val)

[[6. 7. 8.]]


In [36]:
print(b_val_u)

[[ 9. 10. 11.]
 [12. 13. 14.]]
